.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/include Directory Reference" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBksamp\&.h\fP"
.br
.RI "\fIHeader con declaracion de variables y prototipos de funciones\&. \fP"
.in -1c
