.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src Directory Reference" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctionOpt\&.c\fP"
.br
.RI "\fIFunciones que buscan informacion sobre el sistema\&. \fP"
.ti -1c
.RI "file \fBgetBootTime\&.c\fP"
.br
.ti -1c
.RI "file \fBgetSupFs\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBparseFile\&.c\fP"
.br
.ti -1c
.RI "file \fBprintFunctions\&.c\fP"
.br
.RI "\fIContiene las funciones que imprimen informacion\&. \fP"
.ti -1c
.RI "file \fBprintHeader\&.c\fP"
.br
.in -1c
