.TH "Datos" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Datos \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksamp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBcpu\fP [50]"
.br
.ti -1c
.RI "char \fBkernel\fP [50]"
.br
.ti -1c
.RI "long \fBuptime\fP"
.br
.ti -1c
.RI "int \fBfilesystems\fP"
.br
.ti -1c
.RI "double \fBuserTime\fP"
.br
.ti -1c
.RI "double \fBsysTime\fP"
.br
.ti -1c
.RI "double \fBidleTime\fP"
.br
.ti -1c
.RI "char \fBbootTime\fP [50]"
.br
.ti -1c
.RI "int \fBcontextChanges\fP"
.br
.ti -1c
.RI "int \fBprocesses\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ksamp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char bootTime[50]"

.PP
Definition at line 28 of file ksamp\&.h\&.
.SS "int contextChanges"

.PP
Definition at line 29 of file ksamp\&.h\&.
.SS "char cpu[50]"

.PP
Definition at line 20 of file ksamp\&.h\&.
.SS "int filesystems"

.PP
Definition at line 23 of file ksamp\&.h\&.
.SS "double idleTime"

.PP
Definition at line 27 of file ksamp\&.h\&.
.SS "char kernel[50]"

.PP
Definition at line 21 of file ksamp\&.h\&.
.SS "int processes"

.PP
Definition at line 30 of file ksamp\&.h\&.
.SS "double sysTime"

.PP
Definition at line 26 of file ksamp\&.h\&.
.SS "long uptime"

.PP
Definition at line 22 of file ksamp\&.h\&.
.SS "double userTime"

.PP
Definition at line 25 of file ksamp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
