.TH "Flags" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flags \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksamp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBs\fP"
.br
.ti -1c
.RI "int \fBl\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBd\fP"
.br
.ti -1c
.RI "int \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file ksamp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int d"

.PP
Definition at line 46 of file ksamp\&.h\&.
.SS "int f"

.PP
Definition at line 47 of file ksamp\&.h\&.
.SS "int h"

.PP
Definition at line 45 of file ksamp\&.h\&.
.SS "int l"

.PP
Definition at line 44 of file ksamp\&.h\&.
.SS "int s"

.PP
Definition at line 43 of file ksamp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
