.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src/functionOpt.c" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src/functionOpt.c \- Funciones que buscan informacion sobre el sistema\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./include/ksamp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgetMainProgram\fP (struct \fBDatos\fP *datos)"
.br
.ti -1c
.RI "void \fBgetStats\fP (struct \fBDatos\fP *datos)"
.br
.ti -1c
.RI "void \fBcalculateInterval\fP (struct \fBInterval\fP *interval)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Funciones que buscan informacion sobre el sistema\&. 

Incluye funciones que buscan en el sistema de archivos proc de linux y formatean la informacion deseada, guardandola en una estructura de datos apropiada para su impresion\&. 
.PP
\fBSee also:\fP
.RS 4
\fBprintFunctions\&.c\fP 
.RE
.PP

.PP
Definition in file \fBfunctionOpt\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void calculateInterval (struct \fBInterval\fP * interval)"

.PP
Definition at line 72 of file functionOpt\&.c\&.
.SS "void getMainProgram (struct \fBDatos\fP * datos)"

.PP
Definition at line 15 of file functionOpt\&.c\&.
.SS "void getStats (struct \fBDatos\fP * datos)"

.PP
Definition at line 38 of file functionOpt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
