.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src/getSupFs.c" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src/getSupFs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetSupFs\fP (FILE *\fBfp\fP, int *filesystems)"
.br
.RI "\fICalcula la cantidad de sistemas de archivos soportados\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int getSupFs (FILE * fp, int * filesystems)"

.PP
Calcula la cantidad de sistemas de archivos soportados\&. Lee el archivo filesystems y cuenta en un bucle la cantidad de sistemas de archivos soportados por el Kernel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File Descriptor, utilizado para abrir los archivos necesarios como lectura\&. 
.br
\fIfilesystems\fP Puntero a tipo int, donde se va contando la cantidad de filesystems soportados\&. 
.RE
.PP

.PP
Definition at line 10 of file getSupFs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
