.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src/parseFile.c" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src/parseFile.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparseFile\fP (FILE *\fBfp\fP, char \fBpath\fP[], char \fBbefore\fP[], char \fBafter\fP[], char **\fBbuff\fP)"
.br
.RI "\fIParsea un archivo en busca de una cadena de caracteres\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int parseFile (FILE * fp, char path[], char before[], char after[], char ** buff)"

.PP
Parsea un archivo en busca de una cadena de caracteres\&. Recibido un path, una cadena a buscar y delimitadores, busca en el archivo y guarda la cadena en buff\&. Si no puede abrir el archivo termina el programa\&. Busca iterativamente hasta encontrar la primer ocurrencia del string buscado y la recorta en base a los delimitadores\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File Descriptor, usado para abrir un archivo como lectura 
.br
\fIpath[]\fP Cadena de caracteres con la ruta en la que se buscara el archivo 
.br
\fIbefore[]\fP String con el delimitador que se encuentra antes de la cadena deseada 
.br
\fIafter[]\fP String con el delimitador que se encuentra despues de la cadena deseada 
.br
\fIbuff\fP Puntero a char donde se almacena el resultado 
.RE
.PP

.PP
Definition at line 17 of file parseFile\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
