.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src/printHeader.c" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src/printHeader.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprintHeader\fP (FILE *\fBfp\fP, char \fBbuffer\fP[])"
.br
.RI "\fIImprime el mensaje de bienvenida\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int printHeader (FILE * fp, char buffer[])"

.PP
Imprime el mensaje de bienvenida\&. Al iniciar el programa, imprime por consola un mensaje de bienvenida, que consiste en el nombre de la pc donde se esta ejecutando, y la hora y fecha actual\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File Descriptor, utilizado para abrir los archivos necesarios como lectura 
.br
\fIbuffer[]\fP Arreglo de caracteres usado para almacenar las cadenas encontradas 
.RE
.PP

.PP
Definition at line 12 of file printHeader\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
