.TH "/home/gustav/TP1-SO-2016/ksamp/work/code/src/printFunctions.c" 3 "Sat Sep 24 2016" "ksamp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gustav/TP1-SO-2016/ksamp/work/code/src/printFunctions.c \- Contiene las funciones que imprimen informacion\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <asm/param\&.h>\fP
.br
\fC#include '\&.\&./include/ksamp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintMainProgram\fP (struct \fBDatos\fP datos)"
.br
.RI "\fIImprime los datos basicos del sistema\&. \fP"
.ti -1c
.RI "void \fBprintStats\fP (struct \fBDatos\fP datos, int human)"
.br
.RI "\fIMuestra por consola mas informacion sobre el sistema\&. \fP"
.ti -1c
.RI "void \fBprintIntervals\fP (struct \fBInterval\fP data, int human)"
.br
.RI "\fIImprime valores leidos de /proc\&. \fP"
.ti -1c
.RI "void \fBprintDifferences\fP (struct \fBInterval\fP data, int human)"
.br
.RI "\fIImprime las variaciones en los valores leidos de /proc\&. \fP"
.ti -1c
.RI "void \fBprintHelp\fP ()"
.br
.RI "\fIImprime los comandos de ayuda\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const long \fBminute\fP = 60"
.br
.ti -1c
.RI "const long \fBhour\fP = 60 * 60"
.br
.ti -1c
.RI "const long \fBday\fP = 60 * 60 * 24"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contiene las funciones que imprimen informacion\&. 

Se encuentran las funciones que imprimen por consola informacion al usuario\&. Son llamadas de acuerdo a los operadores ingresados al ejecutar el programa\&. 
.PP
Definition in file \fBprintFunctions\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void printDifferences (struct \fBInterval\fP data, int human)"

.PP
Imprime las variaciones en los valores leidos de /proc\&. Es llamada al ingresar la opcion --differential, que muestra el cambio en los valores leidos a lo largo del tiempo ingresado, actualizandose automaticamente\&. Si se solicita la impresion amigable, convierte los valores de memoria de KB a MB para una lectura mas facil de los datos\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Estructura de datos con la informacion necesaria para imprimir 
.br
\fIhuman\fP Flag de impresion amigable 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBcalculateInterval()\fP 
.RE
.PP

.PP
Definition at line 92 of file printFunctions\&.c\&.
.SS "void printHelp (void)"

.PP
Imprime los comandos de ayuda\&. Muestra una lista de los comandos validos del programa, su version corta y larga, y una breve explicacion de cada uno\&. 
.PP
Definition at line 107 of file printFunctions\&.c\&.
.SS "void printIntervals (struct \fBInterval\fP data, int human)"

.PP
Imprime valores leidos de /proc\&. Es llamada al ingresar la opcion --interval, que muestra informacion avanzada sobre los valores leidos a lo largo del tiempo ingresado, actualizandose automaticamente\&. Si se solicita la impresion amigable, convierte los valores de memoria de KB a MB para una lectura mas facil de los datos\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Estructura de datos con la informacion necesaria para imprimir 
.br
\fIhuman\fP Flag de impresion amigable 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBcalculateInterval()\fP 
.RE
.PP

.PP
Definition at line 73 of file printFunctions\&.c\&.
.SS "void printMainProgram (struct \fBDatos\fP datos)"

.PP
Imprime los datos basicos del sistema\&. Muestra el modelo de cpu, la version de kernel del sistema, el tiempo que la pc estuvo encendida, y la cantidad de sistemas de archivos soportados por el kernel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdatos\fP Estructura de datos con la informacion necesaria para imprimir 
.RE
.PP

.PP
Definition at line 23 of file printFunctions\&.c\&.
.SS "void printStats (struct \fBDatos\fP datos, int human)"

.PP
Muestra por consola mas informacion sobre el sistema\&. Imprime el tiempo de uso de la CPU, la hora de inicio del sistema, los cambios de contexto y la cantidad de procesos creados\&. Admite formateo amigable de los datos\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdatos\fP Estructura de datos con la informacion necesaria para imprimir 
.br
\fIhuman\fP Flag de visualizacion de datos de manera amigable 
.RE
.PP

.PP
Definition at line 42 of file printFunctions\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const long day = 60 * 60 * 24"

.PP
Definition at line 14 of file printFunctions\&.c\&.
.SS "const long hour = 60 * 60"

.PP
Definition at line 13 of file printFunctions\&.c\&.
.SS "const long minute = 60"

.PP
Definition at line 12 of file printFunctions\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ksamp from the source code\&.
